# Site settings
title: wxyMoscow
SEOTitle: 王兴宇的博客
header-img: img/home.jpg
email: 122393721@qq.com
description: "这里是 @王兴宇 的个人博客"
keyword: "王兴宇,博客,个人网站,山东大学"
url: "https://wxymoscow.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     wxyMoscow
zhihu_username:     wxyMoscow
github_username:    wxyMoscow
#twitter_username:  huxpro
facebook_username:  王兴宇
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: wxyMoscow






# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

ba_track_id: '10448220'
ba_domain: wxymoscow.github.io

# Google Analytics
ga_track_id: 'UA-88666408-1'            # Format: UA-xxxxxx-xx
ga_domain: wxymoscow.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Xor，<br>add without carry."
sidebar-avatar: /img/wxy2.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Li Zekun",
        href: "https://leezekun.github.io/"
    },
    {
        title: "Yu Peiran",
        href: "https://slientuill.github.io/"
    },
    {
        title: "Ruan Zongming",
        href: "https://ruange.github.io/homepage/"
    },
    {
        title: "Zhao Mingfu",
        href: "https://chicharito999.github.io/Computer-Graphics/"
    },
    {
        title: "Zhang Yupeng",
        href: "https://bluefissure.com/"
    },
    {
        title: "Zhang Haifeng",
        href: "https://basketduck.github.io/"
    },
    {
        title: "Jia Rui",
        href: "https://jiaruisdu.github.io/"
    },
    {
        title: "Lu Baotong",
        href: "https://lueagle.github.io/"
    },
    {
        title: "Liu Tingting",
        href: "https://yjsltt.github.io/"
    },
    {
        title: "Xu Dapeng",
        href: "https://dapeng-xu.github.io/"
    },
    {
        title: "Cao Kun",
        href: "http://kuncao.net/"
    },
    {   
        title: "Ma Yingyin",
        href: "https://yiketree.github.io/"
    },
    {
        title: "Li Zhengxian",
        href: "https://lrenascence.github.io/"
    },
    {
        title: "Zhang Xiao",
        href: "https://j0sephj0estar.github.io/"
    },
    {
        title: "Bu Yuxuan",
        href: "https://buyuxuan.github.io/"
    },
    {
        title: "Xin Zengwei",
        href: "https://heravles.github.io/MyHomepage/"
    },
    {
        title: "Xing Bo",
        href: "https://svenbob.github.io/"
    },
    {
        title: "Guo Cheng",
        href: "https://realguocheng.github.io/"
    },
    {
        title: "Wang Yao",
        href: "https://wangyao-sdu.github.io/"
    },
    {
        title: "Wang Kexin",
        href: "https://52yuanzhao.github.io/homepage/"
    },
    {
        title: "Hou Zhongni",
        href: "https://zhongni.github.io/graphics.github.io/"
    },
    {
        title: "Liu Jingying",
        href: "https://ryinsummers.github.io/"
    },
    {
        title: "Wu Qingli",
        href: "https://dalilili.github.io/Homepage/"
    },
    {
        title: "Zhou Hong",
        href: "https://androidhelen.github.io/homepage/"
    }
]
